# Select the base image
FROM node:18-alpine

# Set the working directory

WORKDIR /app

# Copy the package.json and package-lock.json files

COPY package*.json ./


# Install the dependencies
RUN npm install


# Copy the rest of the application code

COPY . .

# Expose the port the app runs on

EXPOSE 3000

# Serve the app

CMD ["npm", "run","start"]
