version: "3.8"

services:
  server:
    build: ./server
    env_file: .env
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - postgres

  client:
    build: ./client
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - server

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
