import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/ThemeProviders";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/others/Navbar";
import TenstackProvider from "@/components/providers/TenstackProvider";
import { getServerSession } from "next-auth";
import AuthProvider from "@/components/providers/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-wholeBg `}
      >
        <div className="max-w-6xl mx-auto">

          <TenstackProvider>
            <ThemeProvider
              attribute="class"
            >
              <AuthProvider session={session}>
                <Navbar />

                {children}
                <Toaster />
              </AuthProvider>
            </ThemeProvider>

          </TenstackProvider>


        </div>
      </body>
    </html>
  );
}
